### ISSUE TITLE
"intro-bg.jpg" takes way too much time to load

### ISSUE THREAD

**Issue by simnalamburt** [kbknapp/clap-www#2]
I live in South Korea with _>_1Gbps ethernet, but it takes way too much time to load `intro-bg.jpg` properly. I usually don't care the loading speed of images but **1 minute** was too much.

![intro2](https://cloud.githubusercontent.com/assets/4435445/18621080/325342be-7e59-11e6-8a6e-fe6cd82a6e60.png)

I can help optimizing JPEG image but if you really want to use a big fancy background image to the website, using some CDN should be helpful.

By the way `clap-rs` library itself was very awesome.
###### References
- https://www.cloudflare.com/
- https://aws.amazon.com/cloudfront/

**Comment by lifthrasiir** [comment]
Or you can heavily compress the image with a slight loss:

```
$ convert intro-bg.jpg -quality 30 intro-bg-2.jpg
$ wc -c intro-bg*.jpg
  190007 intro-bg-2.jpg
  845040 intro-bg.jpg
 1035047 total
$ compare -metric PSNR intro-bg.jpg intro-bg-2.jpg /dev/null
36.1547
```

(Seems that ImageMagick quality 30 is the minimum quality that preserves a minor detail of laptop surfaces.)

**Comment by simnalamburt** [comment]
@lifthrasiir Do you have a copy of that compressed `intro-bg-2.jpg` file?

**Comment by simnalamburt** [comment]
![compress-bg](https://cloud.githubusercontent.com/assets/4435445/18623070/a3a86362-7e73-11e6-815e-c251b835a46d.jpg)

It looks almost same but much smaller. Download Link: **[compress-bg.zip](https://github.com/kbknapp/clap-www/files/479248/compress-bg.zip)**
